apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-app-deploy
  labels:
    app: banking-app:1.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: banking-app:1.0
  template:
    metadata:
      labels:
        app: banking-app:1.0
    spec:
      containers:
      - name: bankapp-eta-container
        image: dhanashekar/banking-app:1.0
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: banking-app-np-service
  labels:
    app: banking-app:1.0
spec:
  selector:
    app: banking-app:1.0

  type: NodePort
  ports:
  - nodePort: 31030    
    port: 8082
    targetPort: 8082
